### ISSUE TITLE
centos isimluk repo and etc directory create

### ISSUE THREAD

**Issue by ozmend** [theforeman/puppet-foreman_scap_client#30]
Hi,
On CentOS 7 i've had an issue. Puppet master cant install foreman_scap_client and system doest need directory under etc name foreman_openscap_client

I add some lines in inip.pp file to solve this.
it's in attacth

Bye
[isimluk_openscap_init-EDITED_by_OZMEND.pp-27.10.2016.txt](https://github.com/theforeman/puppet-foreman_scap_client/files/555104/isimluk_openscap_init-EDITED_by_OZMEND.pp-27.10.2016.txt)

**Comment by xprazak2** [comment]
Hi,
thanks for raising this issue. From the lines you added I can see that you are pointing your system directly to openscap package in copr. I do not think it is necessary since openscap is in base/updates for CentOS 7 AFAIK:

```
[root@van-tarascio ~]# yum whatprovides openscap
Loaded plugins: fastestmirror, product-id, search-disabled-repos, subscription-manager
This system is registered with Subscription Management, but is not receiving updates. You can use subscription-manager to assign subscriptions.
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
Determining fastest mirrors
 * base: mirror.hosting90.cz
 * epel: mirror.hosting90.cz
 * extras: mirror.hosting90.cz
 * updates: mirror.hosting90.cz
openscap-1.2.5-3.el7.i686 : Set of open source libraries enabling integration of the SCAP line of standards
Repo        : base

openscap-1.2.5-3.el7.x86_64 : Set of open source libraries enabling integration of the SCAP line of standards
Repo        : base

openscap-1.2.9-5.el7_2.i686 : Set of open source libraries enabling integration of the SCAP line of standards
Repo        : updates

openscap-1.2.9-5.el7_2.x86_64 : Set of open source libraries enabling integration of the SCAP line of standards
Repo        : updates

openscap-1.2.9-5.el7_2.x86_64 : Set of open source libraries enabling integration of the SCAP line of standards
Repo        : @updates
```

I suspect foreman_scap_client failed to install because openscap is a dependency and it is not available on your system for some reason. Could you elaborate on your use case?

**Comment by ozmend** [comment]
hi,
i've foreman 1.13 system. i've installed scap proxy. after that it gave me an error that foreman_scap_sclient could not installed because it wasnt in repository. 
i used "yum search foreman_scap_client" but nothing came out.
then i add isimluk repository on my system. for doing this all systems if necessary i wrote this lines in your code. accually, there is some problem in my code also. it runs every time and try to add repo fife again. For this i changed it. 
So my all systems are Centos7. But after install openscap package system cannot find foreman_scap_client.
Do you have any idea?
Thanks

**Comment by xprazak2** [comment]
Hi,
we have foreman_scap_client in our foreman repositories. I would suggest to try the following: 
1) Remove the isimluk repo.
2) Add the following repo into your /etc/yum.repos.d: http://yum.theforeman.org/plugins/1.13/el7/x86_64/
3) Try if puppet run succeeds (with the original script)

I am far from being a puppet expert, but I think your modifications try to add a repo each time because you make it run a wget command when a condition is met, and your condition is based on OS version (which obviously does not change in between runs). I think doing something like:

`file { 'foreman_plugins_repo':`
`path => '/etc/yum/repos.d/foreman_plugins.repo',`
`content => based_on_some_template,`
`ensure => present,`
 `}`

may be a way to do it if you decide to go this way. I realize adding repos manually is unfeasible for large number of hosts, but I do not think a change like this will get in. It kind of clashes with content management that is provided by one of foreman's plugins, katello: http://www.katello.org/

If you want something simple, you could try to set up the repo in %post section of your kickstart.

**Comment by ozmend** [comment]
Hi again,
First, thanks for help. 
i changed init.pp like this

$systemtype = $::operatingsystem ? {
 'CentOS' => 'epel',
 'RedHat' => 'epel',
 'Fedora' => 'fedora',
 'default' => '$operatingsystem',
}

notify { "You have a ${systemtype} system": }

if $systemtype == 'epel' or $systemtype == 'fedora' {
        exec { "isimluk-OpenSCAP-repo" :
                command => "wget -q https://copr.fedorainfracloud.org/coprs/isimluk/OpenSCAP/repo/$systemtype-$operatingsystemmajrelease/isimluk-OpenSCAP-$systemtype-$operatingsystemmajrelease.repo -P /etc/yum.repos.d/",
                path => "/usr/local/bin:/bin:/usr/bin",
                #creates => '/etc/yum.repo.d/isimluk-OpenSCAP-$systemtype-$operatingsystemmajrelease.repo',
                onlyif => 'test ! -f /etc/yum.repo.d/isimluk-OpenSCAP-$systemtype-$operatingsystemmajrelease.repo',
             }
}

But , let put this aside for now.

if i use your suggestion, there will be another issue which nedded to be solved.
rubygem-foreman_scap_client is in the foreman-plugins.repo. foreman client hosts doesnt have it by default. So i need to push this repo into clients after or while installation. This can solve it. But foreman resositories files designed based on its version.
So, for example, if i push foreman-plugin.repo 13.1 to client hosts, after i update foreman main server, client reposiories will stay old. 
In my opinion, if your puppet class have a checking system like check main foreman version on server and use yum for install/update rubygem-foreman_scap_client last version from foreman-plugin.repos for one time into client before run foreman_scap_client, it will be updated all the time and users wont need to push foreman_scap_client package into their clients.
Ofcourse, this is just my idea. For now i'll use use kickstart option that you suggested

Thank you

**Comment by xprazak2** [comment]
Hi,
you are absolutely correct about the shortcomings of my suggestion on how to modify the init.pp in context of updates. 

I see your new example still points to copr repo. Please note that using the copr repo is really not a good idea, the last build of foreman_scap_client in there is version 0.0.1 and it will not work well with foreman 1.13.

> In my opinion, if your puppet class have a checking system like check main foreman version on server and use yum for install/update rubygem-foreman_scap_client last version from foreman-plugin.repos for one time into client before run foreman_scap_client, it will be updated all the time and users wont need to push foreman_scap_client package into their clients.

I am afraid this would bring more problems than solutions. Checking version of a forman server would require a curl call to an endpoint which is not desirable to do from a Puppet class. Moreover, you would have to parse the response and Puppet was simply not designed to do that. 

Even if you pass foreman version into puppet class when applying it,
applying puppet class to host does not trigger foreman_scap_client (it runs from cron), it merely 'yum install' it, so when foreman_scap_client is installed and when it runs a scan are two unrelated things. To update as you suggest, foreman_scap_client would have to call foreman, ask him to check versions, do a puppet run and update foreman_scap_client before each scan is triggered.

It would also mean you have no control over the version of foreman_scap_client, because latest version would always get installed. Besides combining two unrelated workflows together (updating client packages and running compliance scans), it would interfere with what Katello does.

**Comment by ozmend** [comment]
I understand the problem which would be come out.
So, now i implanted foreman-plugin.repo in my kickstart. This works for now.

But i should remaind you that in CentOS7  installing rubygem_foreman-scap-client doesnt create /etc/foreman-scap-client directory. 

Because of that i add these lines into inip.pp
Sorry about i always tamper with your code : )

after package line

_file { '/etc/foreman_scap_client':
    ensure => 'directory',
  }_

**Comment by shlomizadok** [comment]
@ozmend, Thank you for digging into this :)
Would you mind sending us a pull request?

@xprazak2 - This may be related to
http://projects.theforeman.org/issues/10007

2016-11-02 13:11 GMT+02:00 ozmend notifications@github.com:

**Comment by ozmend** [comment]
Sorry for all.
i've used version 0.4 : )
0.6 works great.
Thanks everything

**Comment by shlomizadok** [comment]
@ozmend++ Thanks a lot. Closing :)
